on: push
name: Deploy website on push
jobs.runs-on: windows-latest
    name: Deploy
- name: Checkout
  uses: actions/checkout@v2.3.4
- name: FTP Deploy
  uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          server-dir: www/experimental
