on:                     # トリガーの設定
  push:                 # プッシュした時に実行
            - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@2.0.0   # FTPを使ってサーバーにDeployするアクションを実行
        env:                                        # FTP環境の設定を行う
          FTP_SERVER: ${{ secrets.FTP_SERVER }}     # FTPサーバーのURLを設定
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }} # FTPのユーザー名を設定
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }} # FTPのパスワードを設定
          LOCAL_DIR: experimental                     # どのディレクトリのデータをアップロードするか
          REMOTE_DIR: www/experimental #どのディレクトリにアップロードするか
          ARGS: --delete
